PhoneSmart/Controllers/PhoneModelsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhoneSmart.Data;
using PhoneSmart.Models;
using PhoneSmart.Models.PhoneViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneSmart.Controllers
{
    public class PhoneModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PhoneModelsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: PhoneModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.PhoneModel.ToListAsync());
        }

        //Compare
        public async Task<IActionResult> Compare()
        {

            List<PhoneModel> comparePhones = await _context.PhoneModel.ToListAsync();


            PhoneCompareViewModel vm = new PhoneCompareViewModel();

            vm.PhoneDropdownOne = new SelectList(_context.PhoneModel, "PhoneModelId", "Model");
            vm.PhoneDropdownTwo = new SelectList(_context.PhoneModel, "PhoneModelId", "Model");


            vm.PhoneOne = comparePhones[0];
            vm.PhoneTwo = comparePhones[3];

            return View(vm);
        }


        //Compare Dropdown One
        public async Task<IActionResult> CompareViewOne(int id)
        {
            //List<PhoneModel> firstComparedPhone = await _context.PhoneModel
            //    .Where(p => p.PhoneModelId == id)
            //    .ToListAsync();

            var ComparedPhone = await _context.PhoneModel
            .FirstOrDefaultAsync(m => m.PhoneModelId == id);


            return Ok(ComparedPhone);
        }

        // GET: PhoneModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneModel = await _context.PhoneModel
                .FirstOrDefaultAsync(m => m.PhoneModelId == id);
            if (phoneModel == null)
            {
                return NotFound();
            }

            return View(phoneModel);
        }

        // GET: PhoneModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PhoneModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhoneModelId,Manufacturer,Model,OS,Ram,DisplayType,DisplaySize,RefreshRate,Processor,MainCam,SecondaryCam,FrontCam,Battery,Security,isWirelessCharge,isWaterResist,PhoneURL")] PhoneModel phoneModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(phoneModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(phoneModel);
        }

        // GET: PhoneModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneModel = await _context.PhoneModel.FindAsync(id);
            if (phoneModel == null)
            {
                return NotFound();
            }
            return View(phoneModel);
        }

        // POST: PhoneModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhoneModelId,Manufacturer,Model,OS,Ram,DisplayType,DisplaySize,RefreshRate,Processor,MainCam,SecondaryCam,FrontCam,Battery,Security,isWirelessCharge,isWaterResist,PhoneURL")] PhoneModel phoneModel)
        {
            if (id != phoneModel.PhoneModelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phoneModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneModelExists(phoneModel.PhoneModelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phoneModel);
        }

        // GET: PhoneModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneModel = await _context.PhoneModel
                .FirstOrDefaultAsync(m => m.PhoneModelId == id);
            if (phoneModel == null)
            {
                return NotFound();
            }

            return View(phoneModel);
        }

        // POST: PhoneModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phoneModel = await _context.PhoneModel.FindAsync(id);
            _context.PhoneModel.Remove(phoneModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneModelExists(int id)
        {
            return _context.PhoneModel.Any(e => e.PhoneModelId == id);
        }
    }
}

PhoneSmart/Controllers/PhonesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhoneSmart.Data;
using PhoneSmart.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneSmart.Controllers
{
    public class PhonesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PhonesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Phones
        public async Task<IActionResult> Index(string searchString)
        {
            //Search function
            ViewData["CurrentFilter"] = searchString;

            var applicationDbContext = _context.Phone
            .Include(p => p.PhoneModel)
            .Include(p => p.User)
            .AsQueryable();


            if (!String.IsNullOrEmpty(searchString))
            {
                applicationDbContext = applicationDbContext
                    .Where(p => p.PhoneModel.Manufacturer.Contains(searchString)
                    ||
                    p.PhoneModel.Model.Contains(searchString));
            }
            if (applicationDbContext.Count() < 1)
            {

                return View("SearchError");
            }

            return View(await applicationDbContext.ToListAsync());
            //return View(await _context.Phone.ToListAsync());
        }

        // GET: Phones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone
                .Include(p => p.PhoneModel)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PhoneId == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }


        // GET: Phones/Create
        public IActionResult Create()
        {
            ViewData["PhoneModelId"] = new SelectList(_context.PhoneModel, "PhoneModelId", "Model");
            return View();
        }

        // POST: Phones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhoneId,UserId,Color,Storage,Condition,PhoneModelId,Price")] Phone phone)
        {
            ModelState.Remove("User");
            ModelState.Remove("UserId");
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                phone.UserId = user.Id;
                _context.Add(phone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhoneModelId"] = new SelectList(_context.PhoneModel, "PhoneModelId", "Model", phone.PhoneModelId);
            return View(phone);
        }

        // GET: Phones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone.FindAsync(id);
            if (phone == null)
            {
                return NotFound();
            }
            return View(phone);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhoneId,UserId,Color,Storage,Condition,PhoneModelId,Price")] Phone phone)
        {
            if (id != phone.PhoneId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneExists(phone.PhoneId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phone);
        }

        // GET: Phones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone
                .Include(p => p.PhoneModel)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PhoneId == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phone = await _context.Phone.FindAsync(id);
            _context.Phone.Remove(phone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneExists(int id)
        {
            return _context.Phone.Any(e => e.PhoneId == id);
        }
    }
}

PhoneSmart/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneSmart</title>
    <link rel="stylesheet" href="~/css/site.css" />

    <!--Added for overall style of site-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

</head>
<body>
    <header class="sticky-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @if (SignInManager.IsSignedIn(User))
            {

                // Original singed IN nav bar
<div class="container ">
    @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhoneSmart</a>*@
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://i.imgur.com/7XYSFTr.png" width="30" height="30" class="d-inline-block align-top" alt="">PhoneSmart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <partial name="_LoginPartial" />
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Phones" asp-action="Index">Phones</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="PhoneModels" asp-action="Compare">Compare</a>
            </li>

        </ul>
    </div>
</div> }
else
{
// Original signed OUT nav bar
<div class="container">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhoneSmart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <partial name="_LoginPartial" />
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
            </li>
        </ul>
    </div>
</div>      }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PhoneSmart
            @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Added for new nav bar -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.navbar-light .dmenu').hover(function () {
                $(this).find('.sm-menu').first().stop(true, true).slideDown(150);
            }, function () {
                $(this).find('.sm-menu').first().stop(true, true).slideUp(105)
            });
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>